<h2>Add Quiz for Module {{ $moduleNumber }} of {{ $course->title }}</h2>
<form action="{{ route('quiz.store', ['course' => $course->id, 'module' => $moduleNumber]) }}" method="POST">
    @csrf

    <input type="hidden" name="course_id" value="{{ $course->id }}">
    <input type="hidden" name="module_number" value="{{ $moduleNumber }}">

    <label for="title">Quiz Title:</label>
    <input type="text" name="title" id="title" required>

    <label for="description">Quiz Description:</label>
    <textarea name="description" id="description" required></textarea>

    <hr>

    <label for="question_count">Number of Questions:</label>
    <input type="number" name="question_count" id="question_count" min="1" max="20" value="5" required>

    <div id="questions-section">
        {{-- Questions will be generated by JavaScript --}}
    </div>

    <button type="submit">Create Quiz</button>
</form>

<script>
    document.getElementById('question_count').addEventListener('change', generateQuestions);

    function generateQuestions() {
        const count = parseInt(document.getElementById('question_count').value);
        const container = document.getElementById('questions-section');
        container.innerHTML = '';

        for (let i = 1; i <= count; i++) {
            const qDiv = document.createElement('div');
            qDiv.innerHTML = `
                <h4>Question ${i}</h4>
                <label>Question Text:</label>
                <input type="text" name="questions[${i}][text]" required>

                <label>Number of Options:</label>
                <input type="number" name="questions[${i}][option_count]" min="2" max="6" value="4" onchange="generateOptions(${i}, this.value)" required>

                <div id="options-${i}">
                    <!-- Options will be generated here -->
                </div>
                <hr>
            `;
            container.appendChild(qDiv);
            generateOptions(i, 4); // Default 4 options
        }
    }

    function generateOptions(qIndex, count) {
        const optContainer = document.getElementById(`options-${qIndex}`);
        optContainer.innerHTML = '';

        for (let j = 1; j <= count; j++) {
            optContainer.innerHTML += `
                <div>
                    <label>Option ${j}:</label>
                    <input type="text" name="questions[${qIndex}][options][${j}][text]" required>
                    <label>Is Correct?</label>
                    <input type="radio" name="questions[${qIndex}][correct]" value="${j}" required>
                </div>
            `;
        }
    }

    // Initial load
    generateQuestions();
</script>

